### ISSUE TITLE
Scrum Updates

### ISSUE THREAD

**Issue by Archiving** [JohnTurkson/crypto-trading-platform#1]
Thread your scrum updates here

1. What did you work on this past iteration (past 2 weeks)?
2. What were any major challenges/issues you ran into?
3. What do you plan to work on for this coming iteration (next 2 weeks)?

**Comment by JohnTurkson** [comment]
Scrum Update 1

1. What did you work on this past iteration (past 2 weeks)?
Prototyping layouts and general feature planning
2. What were any major challenges/issues you ran into?
Deciding which features is/will be out of scope
3. What do you plan to work on for this coming iteration (next 2 weeks)?
Overall API design and data modeling

**Comment by andykwan1124** [comment]
1. What did you work on this past iteration (past 2 weeks)?
    Planning out features; categorizing them into 'minimum', 'standard', and 'stretch' goals; and breaking down the minimum goals
2. What were any major challenges/issues you ran into?
    It was a bit difficult to categorize the goals since they all seemed feasible yet complicated at the same time
3. What do you plan to work on for this coming iteration (next 2 weeks)?
    Some of the reusable components (issues like #2 )

**Comment by ryanliu18** [comment]
1. What did you work on this past iteration (past 2 weeks)?
Brainstormed project ideas, planning out the general overview of the project, our goals, target audience, purpose, brainstorming and grouping features into 'minimal', 'standard', and 'stretch' categories.
2. What were any major challenges/issues you ran into?
It was challenging to fully decide on the finalized project idea, scope, features we all wanted, and how the application would look like. (UI) Ultimately I think we have decided on something we all are happy with!
3. What do you plan to work on for this coming iteration (next 2 weeks)?
Some of the components such as Buttons, also work on developing effective styling for components, and for pages such as the User Profile page.

CSID: a2c2b

**Comment by Archiving** [comment]
1. What did you work on this past iteration (past 2 weeks)?
Thought about project ideas, planning and dividing work we need to do for the next 2 weeks, created prototype images of home page and new order page, and grouped features into categories.

2. What were any major challenges/issues you ran into?
It was hard to decide on exactly how we wanted the prototypes to look like. I drew inspiration from many other cryptocurrency trading websites, and finally decided on certain choices.

3. What do you plan to work on for this coming iteration (next 2 weeks)?
Login screen frontend development, and other frontend tasks required of me.

CSID: d8b2b

**Comment by JohnTurkson** [comment]
Scrum Update 2

1. What did you work on this past iteration (past 2 weeks)?
Landing page, sign up, sign in pages
2. What were any major challenges/issues you ran into?
Going through Material UI docs and figuring out React integration
3. What do you plan to work on for this coming iteration (next 2 weeks)?
Backend routes, DB setup, making API calls from React

CSID: f4d2b

**Comment by ryanliu18** [comment]
Scrum Update 2

What did you work on this past iteration (past 2 weeks)?
Coin List and Coin components.
What were any major challenges/issues you ran into?
Learning about Material UI and using the Table and Card components, which was difficult at first but definitely worthwhile. Also had to wrestle with compilation issues for a few hours in the beginning.
What do you plan to work on for this coming iteration (next 2 weeks)?
More components, also adding hooks to ensure we have enough components modifying/updating state.
CSID: a2c2b

**Comment by Archiving** [comment]
Scrum Update 2

What did you work on this past iteration (past 2 weeks)?
1. Portfolio and prices component
What were any major challenges/issues you ran into?
2. Getting a uniform design strategy, learning material UI and making sure my code was elegant and consistent with everyone else's
What do you plan to work on for this coming iteration (next 2 weeks)?
3. Connect more components to flesh out the prices tab, create a graph for the portfolio component, connect to any existing backend
CSID: d8b2b

**Comment by andykwan1124** [comment]
Scrum Update 2

1. What did you work on this past iteration (past 2 weeks)?
Navbar component and improving the Typescript setup of the server folder

2. What were any major challenges/issues you ran into?
Learning about Material UI and the many config options in the `tsconfig.json` file

3. What do you plan to work on for this coming iteration (next 2 weeks)?
Connecting mongoDB to our server and starting on our app's auth system

CSID: n9i2b

**Comment by JohnTurkson** [comment]
Scrum Update 3

1. What did you work on this past iteration (past 2 weeks)?
Infrastructure setup - mongodb, express routes, AWS EC2 + API Gateway
2. What were any major challenges/issues you ran into?
TLS termination with AWS API Gateway
3. What do you plan to work on for this coming iteration (next 2 weeks)?
More express routes, fetching data from the frontend client

CSID: f4d2b

**Comment by ryanliu18** [comment]
Scrum Update 3

1. What did you work on this past iteration (past 2 weeks)?
Added state to Coin and CoinList for the Discover Page with an update button to update state, and added Collapse component to have a drop down menu with more information such as daily low, daily high, etc.
2. What were any major challenges/issues you ran into?
Learning the Collapse component with Table from Material UI, also solving merge conflicts was challenging and time consuming to review the relevant git commands and fix the merge conflicts. Difficult and time consuming at first, but important to understand well for future software engineering work.
3. What do you plan to work on for this coming iteration (next 2 weeks)?
I plan to have the CoinList in the Discover Page retrieve real time data and update state, right now it just has dummy data that is updated with a button.

CSID: a2c2b

**Comment by andykwan1124** [comment]
Scrum Update 3

What did you work on this past iteration (past 2 weeks)?
Server endpoints for login and sign up. General backend auth logic. Started on frontend auth logic.

What were any major challenges/issues you ran into?
Understanding how json web tokens work and how the auth workflow is implemented by companies nowadays.

What do you plan to work on for this coming iteration (next 2 weeks)?
Finish frontend auth logic

CSID: n9i2b

**Comment by Archiving** [comment]
Scrum Update 3

What did you work on this past iteration (past 2 weeks)?
Worked on the portfolio part of the front end

What were any major challenges/issues you ran into?
Understanding more detail into material UI and learning how to use react hooks

What do you plan to work on for this coming iteration (next 2 weeks)?
Finish frontend portfolio development and hook up backend

CSID: d8b2b

**Comment by JohnTurkson** [comment]
Scrum Update 4

What did you work on this past iteration (past 2 weeks)?
API Endpoints, AWS/infrastructure setup

What were any major challenges/issues you ran into?
Deployment/config setup

What do you plan to work on for this coming iteration (next 2 weeks)?
Integrating with additional external APIs, trade and NFT features

CSID: f4d2b

**Comment by Archiving** [comment]
Scrum Update 4

What did you work on this past iteration (past 2 weeks)?
API Endpoints

What were any major challenges/issues you ran into?
Planning and following server endpoint architecture

What do you plan to work on for this coming iteration (next 2 weeks)?
Integrating with frontend components, adding more API endpoints related to trading/portfolio management and display

CSID: d8b2b

**Comment by ryanliu18** [comment]
Scrum Update 4

What did you work on this past iteration (past 2 weeks)?
Charts, CoinList (Frontend components)

What were any major challenges/issues you ran into?
Figuring out which charts api to use, and how they worked, I tried a few different ones at first and they didn't work the way I wanted it to, but eventually found one that worked fine after a lot of trial and error.

What do you plan to work on for this coming iteration (next 2 weeks)?
Making charts and coinlists display real time data and perhaps some historical data, helping out/ finishing trade, and portfolio functionality. 

CSID: a2c2b

**Comment by andykwan1124** [comment]
Scrum Update 4

What did you work on this past iteration (past 2 weeks)?
Frontend auth structure, setup, and testing

What were any major challenges/issues you ran into?
Understanding how React.context works

What do you plan to work on for this coming iteration (next 2 weeks)?
Profile page

CSID: n9i2b

**Comment by JohnTurkson** [comment]
Scrum Update 5

What did you work on this past iteration (past 2 weeks)?
Automated AWS deploys with CodeDeploy, VM provisioning and DNS setup, serverless function changes.

What were any major challenges/issues you ran into?
Deployment/config setup

What do you plan to work on for this coming iteration (next 2 weeks)?
Helping with trade + more user signup features

CSID: f4d2b

**Comment by andykwan1124** [comment]
Scrum Update 5

What did you work on this past iteration (past 2 weeks)?
Setting up user profile

What were any major challenges/issues you ran into?
Figuring out where to put my changes after the backend refactoring efforts.

What do you plan to work on for this coming iteration (next 2 weeks)?
Finishing user profile, bookmarking cryptos

CSID: n9i2b

**Comment by ryanliu18** [comment]
Scrum Update 5

What did you work on this past iteration (past 2 weeks)?
Charts, connecting to real time price data and rendering real time price data.

What were any major challenges/issues you ran into?
Wrestling with React Highcharts API, the default behaviour prevents re-renders of the chart since re-rendering is expensive, so I had to dive into the documentation to fix this. Also, the timestamp from our websockets connection was not of the right units, so I had to apply a linear transformation to get the current time units.

What do you plan to work on for this coming iteration (next 2 weeks)?
Finishing charts and coin table, helping out with trade, bookmarking crypto.

CSID: a2c2b

**Comment by Archiving** [comment]
Scrum Update 5

What did you work on this past iteration (past 2 weeks)
Developing a frontend connection for the backend endpoints developed last sprint, along with more backend support

What were any major challenges/issues you ran into?
Working with our backend structure and developing more backend endpoints in order to achieve functional trading and portfolio display

What do you plan to work on for this coming iteration (next 2 weeks)?
Finishing frontend and backend connections for the portfolio endpoints 

CSID: d8b2b
