### ISSUE TITLE
Price value loading infinitely

### ISSUE THREAD

**Issue by Success-Guy** [JohnTurkson/crypto-trading-platform#78]
# Great project

According to [the demo page crypto.johnturkson.com](https://crypto.johnturkson.com/overview)
## On prices page
Prices, daily change and daily net changes are not loading - just shows loading

## On overview pages
 Same thing happen, the value for ''value'' is not loading too.
 The unit is not specified in deposit, that if amount deposited in USD or the coin value: this is confusing - please update the input placeholder.

I could done this but I'm not typescript user.

**Comment by JohnTurkson** [comment]
Thanks for creating this issue. Currently, the project is not being actively maintained as we're a little busy with our full-time jobs at the moment, and price updates have been disabled to save on AWS costs. We're aware that v1.0 has some rough edges, but if we ever decide to build a v2.0, we'll definitely try to address most of these issues.

**Comment by Success-Guy** [comment]
Alright.
Thanks.
